export type {
  StrapiMetaItem,
  StrapiFeatureItem,
  StrapiIncludedCard,
  StrapiFaqContent,
  StrapiMedia,
  StrapiCategory,
  StrapiPersona,
  StrapiCoupon,
  StrapiEarlyOffer,
  StrapiGalleryTab,
  StrapiDividerSectionBlock,
  StrapiFeaturesSectionBlock,
  StrapiPersonasSectionBlock,
  StrapiIncludedSectionBlock,
  StrapiRichTextBlock,
  StrapiFaqBlock,
  StrapiDescriptionBlock,
  StrapiTemplateDetail,
} from "@/types/strapi";
